### ISSUE TITLE
Backup rt index

### ISSUE THREAD

**Issue by BarryRufer** [SiroDiaz/sphinxql#6]
Before backup need command `FLUSH RTINDEX rt`

```connection.getQueryBuilder().query(`FLUSH RTINDEX ?`, ['rt'])```
Maybe added ```connection.getQueryBuilder().flush('rt')```

**Comment by SiroDiaz** [comment]
> connection.getQueryBuilder().query(`FLUSH RTINDEX ?`, ['rt'])

Yes, you can run that command with the `query` method.

> Maybe added connection.getQueryBuilder().flush('rt')

sure, all commands will have their own method. The query method is thought as a temporal solution.

**Comment by SiroDiaz** [comment]
Now you can use in 0.2.2 FLUSH RTINDEX using the following code:

```javascript
connection.getQueryBuilder()
  .flushRTIndex('my_rt_index')
  .execute()
  .then((result, fields) => {
    console.log(result);
  });
```

Is more verbose but will avoid colision between different FLUSH commands allowed with Manticore/Sphinx.
